server:
  port: 8086

spring:
  jpa:
    hibernate:
      ddl-auto:  update  # Hibernate ddl auto (create, create-drop, validate, update)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect  # The SQL dialect makes Hibernate generate better SQL for the chosen database

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://mysqldb/generator_app?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false"
    username: "root"
    password: "root"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000

  flyway:
    enabled: true
    url: jdbc:mysql://mysqldb/mysql
    schemas: generator_app
    user: "root"
    password: "root"
    locations: classpath:db/migration